### ISSUE TITLE
Support Different AI Type for Player 2

### ISSUE THREAD

**Issue by umtcnshn** [vwxyzjn/gym-microrts#2] opened 2020-02-25 07:21 UTC
First of all, thanks for this wonderful MicroRTS gym wrapper. From what I understand from the sample code that you shared, there is only one player (blue) that can take actions. My question is how we can get the workers of the other player (red) to move. I was able to add a red worker by modifying to map files in the folder. But I couldn't get these workers to move/harvest. Thanks in advance.

**Comment by vwxyzjn** [comment] 2020-02-25 17:06
Thanks for the kind words. Some required changes are:

1. Using JNIAI (which take actions and feedback observation to the python side) for the second AI in https://github.com/vwxyzjn/microrts/blob/master/src/tests/JNIClient.java. Currently, the second AI is a passive AI, which is the reason why you couldn't move the units from the red players (https://github.com/vwxyzjn/microrts/blob/d1fc2e66ad0e53ac015187470f31b247a4bd2a9a/src/tests/JNIClient.java#L90). To further support this, we need to create interfaces to step the second JNIAI as well.

2. Then on the python side, we need to find interfaces support stepping methods on two agents. Currently, I am not aware of any common interfaces (i.e. as common as the gym interface) used for multi-agent training.

Overall, I think this will be a fair amount of work, but this is something that I able definitely support in the future. As of the current moment, if you would like to work on it, I could provide you with the necessary build instructions. Otherwise, I might have to focus on my current research for the next month. Sorry :(

**Comment by vwxyzjn** [comment] 2020-02-25 17:14
Perhaps the most popular common multiple agent interface is https://github.com/koulanurag/ma-gym

**Comment by umtcnshn** [comment] 2020-02-26 12:01
Thanks for the detailed answer. I really appreciate it. At this current state, can we choose other options for the second AI other than the passive one? Such as taking random actions? Or the current interface only allows for a passive AI at this stage?

**Comment by vwxyzjn** [comment] 2020-02-26 12:45
Actually, The second AI could be any existing AI on the java side, For example, randomAI, MCTSAI, etc. They could be very Easily toggled in the current interface.

**Comment by vwxyzjn** [comment] 2020-02-26 21:47
1Please use the following command to update microrts jar file
```bash
$ rm ~/microrts -fR && mkdir ~/microrts && \
wget -O ~/microrts/microrts.zip http://microrts.s3.amazonaws.com/microrts/artifacts/202002262139.microrts.zip && \
unzip ~/microrts/microrts.zip -d ~/microrts/ && \
rm ~/microrts/microrts.zip```

then run the following script
```python
import gym
import gym_microrts
import time
try:
    env = gym.make("MicrortsGlobalAgentRandomEnemy10x10FrameSkip9-v0")
    env.action_space.seed(0)
    env.reset()
    for i in range(10000):
        env.render()
        time.sleep(0.2)
        obs = env.step(env.action_space.sample())
        if env.step(env.action_space.sample())[2]:
            print("done")
            break
    #env.close()
except Exception as e:
    print(e)
    print(e.stacktrace())
```
You will not have to mess with the java side to experiment with the other AIs. Checked out how it's done in the referenced [commit](https://github.com/vwxyzjn/gym-microrts/commit/f10c92bfb5c1180121661158992cf2f2ff794c89) above. You have the flexibility to import every possible AI from https://github.com/vwxyzjn/microrts/tree/master/src/ai

**Comment by vwxyzjn** [comment] 2020-02-26 21:47
Closing now. I will reopen if you have any other of questions.

**Comment by vwxyzjn** [comment] 2020-02-26 21:49
The general support for multi-agent well come in the long run.

**Comment by vwxyzjn** [comment] 2020-02-27 20:32
@umtcnshn Can you confirm if this works for you?

**Comment by umtcnshn** [comment] 2020-02-28 07:54
Sorry to respond late. Yes it solved my problem. Thanks for all your detailed answers, I really appreciate it. Good luck with your research, I will stay tuned for it.

**Comment by umtcnshn** [comment] 2020-08-07 11:05
Hi again, I want to ask a question regarding different options for the second AI. Since it is related to my first problem, I want to reopen this issue. As you said, I am now able to import every AI from the repo: https://github.com/vwxyzjn/microrts/tree/master/src/ai. But some AIs like LightRush requires a UnitTypeTable object in their constructors. Is there a way to import the UnitTypeTable object from the Java side into Python? Or is this object already present in the Python side and if so how can I access it to use for the AIs from the ai.abstraction class? Thanks for your answers.

**Comment by vwxyzjn** [comment] 2020-08-07 14:06
Yes the utt is already in the class. Maybe trying using `env.utt`. Let me know if it helps.

**Comment by vwxyzjn** [comment] 2020-08-07 14:07
On a related note I feel self-play could be implemented in the following way: https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/experiments/ppo_self_play.py

**Comment by changpowei** [comment] 2020-08-10 02:05
Hi @vwxyzjn ! Very appreciated for this MicroRTS gym wrapper. I'm currently trying to solve the MicroRTS with some Reinforcement Learning skill. And it seems to face the problems same as @umtcnshn said, it requires a UnitTypeTable object when I import some AIs(like WorkerRush, LightRush...etc). And I solved above question using below method:

def WorkerRush():
    from ai.abstraction import WorkerRush
    from rts.units import UnitTypeTable
    utt = UnitTypeTable()
    return  WorkerRush(utt)

After define the WorkerRush AI like this,  I'm setting the ai2 of "MicrortsAttackSparseReward-v1" to WorkerRush which is different from original randomAI. Then I modified to this environment in "hello_world.py". As shown below, the WorkerRush doesn't work appropriately.

Thanks for your answers.
![4w0ga-br5wx](https://user-images.githubusercontent.com/22905460/89747154-0474ef80-daf0-11ea-8720-f35c5519df78.gif)

**Comment by vwxyzjn** [comment] 2020-08-10 04:12
Hi @umtcnshn @changpowei ,

Thanks for the valuable bug report. Please update microrts using the following command 
```
rm ~/microrts -fR && mkdir ~/microrts && \
wget -O ~/microrts/microrts.zip http://microrts.s3.amazonaws.com/microrts/artifacts/202008100000.microrts.zip && \
unzip ~/microrts/microrts.zip -d ~/microrts/ && \
rm ~/microrts/microrts.zip
```
Then the following should work

```
import gym
import gym_microrts
import time
from gym.wrappers import TimeLimit, Monitor

try:
    env = gym.make("MicrortsWorkerRush-v1")
    env = Monitor(env, f'videos', force=True)
    env.action_space.seed(0)
    env.reset()
    for i in range(10000):
        time.sleep(0.2)
        obs = env.step(env.action_space.sample())
        next_obs, reward, done, info = env.step(env.action_space.sample())
        if done:
            print("done")
            break
    #env.close()
except Exception as e:
    print(e)
    print(e.stacktrace())
```

![demo](https://user-images.githubusercontent.com/5555347/89751390-d8c91980-da9d-11ea-8b9a-4daba182d68f.gif)

See the related code for how this is achieved. https://github.com/vwxyzjn/gym-microrts/commit/5b50735052bc1c45a502141a7ad223c3e72840e7

**Comment by changpowei** [comment] 2020-08-10 06:51
Thanks for replying! After update the microrts.jar and codes that u just modified, it still have problem here. Please help debugging.
1. It seems missing some code when launch the JVM 
![擷取選取區域_285](https://user-images.githubusercontent.com/22905460/89757481-f5099c80-db17-11ea-84a2-9189ba4f835c.png)
2.After adding the code, some error pop up. It seems problem of Java version. 
![擷取選取區域_286](https://user-images.githubusercontent.com/22905460/89757815-e5d71e80-db18-11ea-9741-08c7e32cbaa5.png)

Thanks for help debugging!

**Comment by changpowei** [comment] 2020-08-10 08:08
> Thanks for replying! After update the microrts.jar and codes that u just modified, it still has some problems here. Please help debugging.
> 
> 1. It seems missing some code when launching the JVM
>    ![擷取選取區域_285](https://user-images.githubusercontent.com/22905460/89757481-f5099c80-db17-11ea-84a2-9189ba4f835c.png)
> 2. After adding the code, some error pop up. It seems problem of Java version.
>    ![擷取選取區域_286](https://user-images.githubusercontent.com/22905460/89757815-e5d71e80-db18-11ea-9741-08c7e32cbaa5.png)
> 
> Thanks for help debugging!

I found that the problem is that the JDK version is too low. I just update Java version to OpenJDK 14, and it works smoothly. 
Thx again.

**Comment by umtcnshn** [comment] 2020-08-11 05:50
Thank you all @vwxyzjn @changpowei. As @changpowei said, after I updated the JDK version, everything works smoothly. On a side note, I am running the game on a Windows 10 machine. Windows users should update the JAVA_HOME path in the Environment Variables with the correct JDK version so that you don't get the error @changpowei mentions.

**Comment by vwxyzjn** [comment] 2020-08-11 17:07
Thanks everyone for the kind discussion and support. This issue is now closed. For related issue on self-play, #6 should host related discussions instead. Closing this issue for now.

**Comment by vwxyzjn** [comment] 2020-08-11 17:08
@umtcnshn @changpowei The reason the JDK version has been an issue is because our CI/CD server is down and I had to manually build a release myself, whihc is built using JDK 14

**Closed by vwxyzjn** 2020-08-11 17:07 UTC
